// Copyright Epic Games, Inc. All Rights Reserved.
#pragma once

#pragma pack(push, 8)

EXTERN_C typedef struct EOS_AuthHandle* EOS_HAuth;

/**
 * All possible types of login methods, availability depends on permissions granted to the client
 *
 * @see EOS_Auth_Login
 * @see EOS_Auth_Credentials
 */
EOS_ENUM(EOS_ELoginCredentialType,
	/** Email / Password. Use of this login type is restricted. */
	EOS_LCT_Password = 0,
	/** Exchange code, typically generated by launcher */
	EOS_LCT_ExchangeCode = 1,
	/**
	 * Long-lived access token that is stored in the local device to allow persisting a user login session over game sessions.
	 * The persistent access token is stored in a keychain owned by the currently logged in user of the local device.
	 *
	 * When using this login type with EOS_Auth_Login, if existing access token is not found in the local keychain, the error result EOS_EResult::EOS_InvalidAuth is returned.
	 */
	EOS_LCT_PersistentAuth = 2,
	/** Initiate a pin grant completed via an external device */
	EOS_LCT_DeviceCode = 3,
	/** Request credentials from the EOS SDK Dev Auth Tool */
	EOS_LCT_Developer = 4,
	/** Refresh token */
	EOS_LCT_RefreshToken = 5,
	/** Initiate a login through the account portal. Cannot be used on consoles. */
	EOS_LCT_AccountPortal = 6
);

/** The most recent version of the EOS_Auth_Token struct. */
#define EOS_AUTH_TOKEN_API_002 2

/**
 * Types of auth tokens
 *
 * @see EOS_Auth_CopyUserAuthToken
 * @see EOS_Auth_Token
 */
EOS_ENUM(EOS_EAuthTokenType,
	/** Auth token is for a validated client */
	EOS_ATT_Client = 0,
	/** Auth token is for a validated user */
	EOS_ATT_User = 1
);

/** A structure that contains an auth token. These structures are created by EOS_Auth_CopyUserAuthToken and must be passed to EOS_Auth_Token_Release. */
EOS_STRUCT(EOS_Auth_Token002, (
	/** Version of the API */
	int32_t ApiVersion;
	/** Name of the app related to the client id involved with this token */
	const char* App;
	/** Client id that requested this token */
	const char* ClientId;
	/** User account associated with this auth token */
	EOS_EpicAccountId AccountId;
	/** Signature of the access token */
	const char* AccessToken;
	/** Time before the access token expires, in seconds, relative to the call to EOS_Auth_CopyUserAuthToken */
	double ExpiresIn;
	/** Absolute time in UTC before the access token expires, in ISO 8601 format */
	const char* ExpiresAt;
	/** Type of auth token */
	EOS_EAuthTokenType AuthType;
	/** Signature of the refresh token */
	const char* RefreshToken;
	/** Time before the access token expires, in seconds, relative to the call to EOS_Auth_CopyUserAuthToken */
	double RefreshExpiresIn;
	/** Absolute time in UTC before the refresh token expires, in ISO 8601 format */
	const char* RefreshExpiresAt;
));

/**
 * Release the memory associated with an EOS_Auth_Token structure. This must be called on data retrieved from EOS_Auth_CopyUserAuthToken.
 *
 * @param AuthToken - The auth token structure to be released
 *
 * @see EOS_Auth_Token
 * @see EOS_Auth_CopyUserAuthToken
 */
EOS_DECLARE_FUNC(void) EOS_Auth_Token_Release(EOS_Auth_Token* AuthToken);

/** The most recent version of the EOS_Auth_Credentials struct. */
#define EOS_AUTH_CREDENTIALS_API_002 2

/**
 * A structure that contains login credentials. What is required is dependent on the type of login being initiated.
 * 
 * This is part of the input structure EOS_Auth_LoginOptions and related to device auth
 *
 * EOS_LCT_Password - (id/token) required with email/password
 * EOS_LCT_ExchangeCode - (token) exchange code
 * EOS_LCT_PersistentAuth - (N/A) login using previously stored persistent access credentials for the local user of the device
 * EOS_LCT_DeviceCode - (N/A) initiate a pin grant completed via an external device
 *
 * @see EOS_ELoginCredentialType
 * @see EOS_Auth_Login
 * @see EOS_Auth_DeletePersistentAuthOptions
 */ 
EOS_STRUCT(EOS_Auth_Credentials002, (
	/** Version of the API */
	int32_t ApiVersion;
	/** Id of the user logging in, based on EOS_ELoginCredentialType */
	const char* Id;
	/** Credentials or token related to the user logging in */
	const char* Token;
	/** Type of login. Needed to identify the auth method to use */
	EOS_ELoginCredentialType Type;
));

/** The most recent version of the EOS_Auth_PinGrantInfo struct. */
#define EOS_AUTH_PINGRANTINFO_API_002 2

/**
 * These structures are returned by EOS_Auth_LoginCallbackInfo.  
 * The data inside should be exposed to the user for entry on a secondary device
 * All data must be copied out before the completion of this callback
 */
EOS_STRUCT(EOS_Auth_PinGrantInfo002, (
	/** Version of the API */
	int32_t ApiVersion;
	/** Code the user must input on an external device to activate the login */
	const char* UserCode;
	/** The end-user verification URI. Users can be asked to manually type this into their browser. */
	const char* VerificationURI;
	/** Time the user has, in seconds, to complete the process or else timeout */
	int32_t ExpiresIn;
	/** A verification URI that includes the user code. Useful for non-textual transmission. */
	const char* VerificationURIComplete;
));

/* Flags that describe user permissions */
EOS_ENUM(EOS_EAuthScopeFlags,
	EOS_AS_NoFlags = 0x0,
	/** Permissions to see your account ID, display name, language and country */
	EOS_AS_BasicProfile = 0x1,
	/** Permissions to see a list of your friends who use this application */
	EOS_AS_FriendsList = 0x2,
	/** Permissions to set your online presence and see presence of your friends */
	EOS_AS_Presence = 0x4
);

/** A set of bitwise operators provided when the enum is provided as an `enum class`. */
#if defined(__cplusplus) && (__cplusplus >= 201103L || (defined(_MSC_VER) && defined(_MSVC_LANG) && _MSVC_LANG >= 201103L))
inline constexpr EOS_EAuthScopeFlags operator|(EOS_EAuthScopeFlags Left, EOS_EAuthScopeFlags Right) { return static_cast<EOS_EAuthScopeFlags>((__underlying_type(EOS_EAuthScopeFlags))Left | (__underlying_type(EOS_EAuthScopeFlags))Right); }
inline constexpr EOS_EAuthScopeFlags operator&(EOS_EAuthScopeFlags Left, EOS_EAuthScopeFlags Right) { return static_cast<EOS_EAuthScopeFlags>((__underlying_type(EOS_EAuthScopeFlags))Left & (__underlying_type(EOS_EAuthScopeFlags))Right); }
inline constexpr EOS_EAuthScopeFlags operator^(EOS_EAuthScopeFlags Left, EOS_EAuthScopeFlags Right) { return static_cast<EOS_EAuthScopeFlags>((__underlying_type(EOS_EAuthScopeFlags))Left ^ (__underlying_type(EOS_EAuthScopeFlags))Right); }
inline constexpr EOS_EAuthScopeFlags& operator|=(EOS_EAuthScopeFlags& Left, EOS_EAuthScopeFlags Right) { return Left = Left | Right; }
inline constexpr EOS_EAuthScopeFlags& operator&=(EOS_EAuthScopeFlags& Left, EOS_EAuthScopeFlags Right) { return Left = Left & Right; }
inline constexpr EOS_EAuthScopeFlags& operator^=(EOS_EAuthScopeFlags& Left, EOS_EAuthScopeFlags Right) { return Left = Left ^ Right; }
#endif

/** The most recent version of the EOS_Auth_Login API. */
#define EOS_AUTH_LOGIN_API_002 2

/**
 * Input parameters for the EOS_Auth_Login Function.
 */
EOS_STRUCT(EOS_Auth_LoginOptions002, (
	/** Version of the API */
	int32_t ApiVersion;
	/** Credentials specified for a given login method */
	const EOS_Auth_Credentials* Credentials;
	/** Auth scope flags are permissions to request from the user while they are logging in. This is a bitwise-or union of EOS_EAuthScopeFlags flags defined above */
	EOS_EAuthScopeFlags ScopeFlags;
));

/**
 * Output parameters for the EOS_Auth_Login Function.
 */
EOS_STRUCT(EOS_Auth_LoginCallbackInfo, (
	enum { k_iCallback = k_iAuthCallbackBase + 1 };
	/** Result code for the operation. EOS_Success is returned for a successful query, otherwise one of the error codes is returned. See eos_common.h */
	EOS_EResult ResultCode;
	/** Context that was passed into EOS_Auth_Login */
	void* ClientData;
	/** Account ID of the local player requesting the information */
	EOS_EpicAccountId LocalUserId;
	/** Optional data returned in the middle of a EOS_LCT_DeviceCode request */
	const EOS_Auth_PinGrantInfo* PinGrantInfo;
));

/**
 * Function prototype definition for callbacks passed to EOS_Auth_Login
 * @param Data A EOS_Auth_LoginCallbackInfo containing the output information and result
 */
EOS_DECLARE_CALLBACK(EOS_Auth_OnLoginCallback, const EOS_Auth_LoginCallbackInfo* Data);

/** The most recent version of the EOS_Auth_Logout API. */
#define EOS_AUTH_LOGOUT_API_001 1

/**
 * Input parameters for the EOS_Auth_Logout Function.
 */
EOS_STRUCT(EOS_Auth_LogoutOptions001, (
	/** Version of the API */
	int32_t ApiVersion;
	/** Account ID of the local player requesting the information */
	EOS_EpicAccountId LocalUserId;
));

/**
 * Output parameters for the EOS_Auth_Logout Function.
 */
EOS_STRUCT(EOS_Auth_LogoutCallbackInfo, (
	enum { k_iCallback = k_iAuthCallbackBase + 2 };
	/** Result code for the operation. EOS_Success is returned for a successful query, otherwise one of the error codes is returned. See eos_common.h */
	EOS_EResult ResultCode;
	/** Context that was passed into EOS_Auth_Login */
	void* ClientData;
	/** Account ID of the local player requesting the information */
	EOS_EpicAccountId LocalUserId;
));

/**
 * Function prototype definition for callbacks passed to EOS_Auth_Logout
 * @param Data A EOS_Auth_LogoutCallbackInfo containing the output information and result
 */
EOS_DECLARE_CALLBACK(EOS_Auth_OnLogoutCallback, const EOS_Auth_LogoutCallbackInfo* Data);

/** The most recent version of the EOS_Auth_VerifyUserAuth API. */
#define EOS_AUTH_VERIFYUSERAUTH_API_001 1

/**
 * Input parameters for the EOS_Auth_VerifyUserAuth Function.
 * This operation is destructive, the pointer will remain the same but the data pointers inside will update
 */
EOS_STRUCT(EOS_Auth_VerifyUserAuthOptions001, (
	/** Version of the API */
	int32_t ApiVersion;
	/** Auth token to verify against the backend service */
	const EOS_Auth_Token* AuthToken;
));

/**
 * Output parameters for the EOS_Auth_VerifyUserAuth Function.
 */
EOS_STRUCT(EOS_Auth_VerifyUserAuthCallbackInfo, (
	enum { k_iCallback = k_iAuthCallbackBase + 3 };
	/** Result code for the operation. EOS_Success is returned for a successful query, otherwise one of the error codes is returned. See eos_common.h */
	EOS_EResult ResultCode;
	/** Context that was passed into EOS_Auth_Login */
	void* ClientData;
));

/**
 * Function prototype definition for callbacks passed to EOS_Auth_VerifyUserAuth
 * @param Data A EOS_Auth_VerifyUserAuthCallbackInfo containing the output information and result
 */
EOS_DECLARE_CALLBACK(EOS_Auth_OnVerifyUserAuthCallback, const EOS_Auth_VerifyUserAuthCallbackInfo* Data);


/** The most recent version of the EOS_Auth_CopyUserAuthTokenOptions API. */
#define EOS_AUTH_COPYUSERAUTHTOKEN_API_001 1

/**
 * Input parameters for the EOS_Auth_CopyUserAuthToken Function.
 */
EOS_STRUCT(EOS_Auth_CopyUserAuthTokenOptions001, (
	/** Version of the API to use */
	int32_t ApiVersion;
));


/** The most recent version of the AddNotifyLoginStatusChanged API. */
#define EOS_AUTH_ADDNOTIFYLOGINSTATUSCHANGED_API_001 1

/**
 * Input parameters for the AddNotifyLoginStatusChanged Function.
 */
EOS_STRUCT(EOS_Auth_AddNotifyLoginStatusChangedOptions001, (
	/** Version of the API to use */
	int32_t ApiVersion;
));


/** The most recent version of the EOS_Auth_DeletePersistentAuth API. */
#define EOS_AUTH_DELETEPERSISTENTAUTH_API_001 1

/**
 * Input parameters for the EOS_Auth_DeletePersistentAuth Function.
 */
EOS_STRUCT(EOS_Auth_DeletePersistentAuthOptions001, (
	/** Version of the API */
	int32_t ApiVersion;
));

/**
 * Output parameters for the EOS_Auth_DeletePersistentAuth Function.
 */
EOS_STRUCT(EOS_Auth_DeletePersistentAuthCallbackInfo, (
	enum { k_iCallback = k_iAuthCallbackBase + 4 };
	/** Result code for the operation. EOS_Success is returned for a successful query, otherwise one of the error codes is returned. See eos_common.h */
	EOS_EResult ResultCode;
	/** Context that was passed into EOS_Auth_DeletePersistentAuth */
	void* ClientData;
));

/**
 * Function prototype definition for callbacks passed to EOS_Auth_DeletePersistentAuth
 * @param Data A EOS_Auth_DeletePersistentAuthCallbackInfo containing the output information and result
 */
EOS_DECLARE_CALLBACK(EOS_Auth_OnDeletePersistentAuthCallback, const EOS_Auth_DeletePersistentAuthCallbackInfo* Data);


/**
 * Output parameters for the EOS_Auth_OnLoginStatusChangedCallback Function.
 */
EOS_STRUCT(EOS_Auth_LoginStatusChangedCallbackInfo, (
	enum { k_iCallback = k_iAuthCallbackBase + 5 };
	/** Context that was passed into EOS_Auth_AddNotifyLoginStatusChanged */
	void* ClientData;
	/** Account ID of the local player whose status has changed */
	EOS_EpicAccountId LocalUserId;
	/** The status prior to the change */
	EOS_ELoginStatus PrevStatus;
	/** The status at the time of the notification */
	EOS_ELoginStatus CurrentStatus;
));

/**
 * Function prototype definition for notifications that come from EOS_Auth_AddNotifyLoginStatusChanged
 *
 * @param Data A EOS_Auth_LoginStatusChangedCallbackInfo containing the output information and result
 */
EOS_DECLARE_CALLBACK(EOS_Auth_OnLoginStatusChangedCallback, const EOS_Auth_LoginStatusChangedCallbackInfo* Data);

#pragma pack(pop)
